-- MySQL Script generated by MySQL Workbench
-- 06/18/16 11:49:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tds
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tds` ;

-- -----------------------------------------------------
-- Schema tds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tds` DEFAULT CHARACTER SET utf8 ;
USE `tds` ;

-- -----------------------------------------------------
-- Table `tds`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tds`.`grupo` ;

CREATE TABLE IF NOT EXISTS `tds`.`grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `permissao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tds`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tds`.`usuario` ;

CREATE TABLE IF NOT EXISTS `tds`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  `grupo_id` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`, `grupo_id`),
  INDEX `fk_usuario_grupo_idx` (`grupo_id` ASC),
  CONSTRAINT `fk_usuario_grupo`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `tds`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tds`.`medidorFamilia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tds`.`medidorFamilia` ;

CREATE TABLE IF NOT EXISTS `tds`.`medidorFamilia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tds`.`medidorImagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tds`.`medidorImagem` ;

CREATE TABLE IF NOT EXISTS `tds`.`medidorImagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imagem` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tds`.`medidorTerminal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tds`.`medidorTerminal` ;

CREATE TABLE IF NOT EXISTS `tds`.`medidorTerminal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `terminalsArrangement` VARCHAR(50) NULL,
  `terminals` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tds`.`medidorPendencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tds`.`medidorPendencias` ;

CREATE TABLE IF NOT EXISTS `tds`.`medidorPendencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataDeAbertura` DATE NULL,
  `dataDeConclusao` DATE NULL,
  `prioridade` INT NULL,
  `observacoes` LONGTEXT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_medidorPendencias_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_medidorPendencias_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `tds`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tds`.`medidorAtribGerais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tds`.`medidorAtribGerais` ;

CREATE TABLE IF NOT EXISTS `tds`.`medidorAtribGerais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `eletrapartnumber` VARCHAR(20) NULL,
  `informacao` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tds`.`medidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tds`.`medidor` ;

CREATE TABLE IF NOT EXISTS `tds`.`medidor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medidorFamilia_id` INT NOT NULL,
  `medidorImagem_id` INT NOT NULL,
  `medidorTerminal_id` INT NOT NULL,
  `medidorPendencias_id` INT NOT NULL,
  `medidorAtribGerais_id` INT NOT NULL,
  PRIMARY KEY (`id`, `medidorFamilia_id`, `medidorImagem_id`, `medidorTerminal_id`, `medidorPendencias_id`, `medidorAtribGerais_id`),
  INDEX `fk_medidor_medidorFamilia1_idx` (`medidorFamilia_id` ASC),
  INDEX `fk_medidor_medidorDesenho1_idx` (`medidorImagem_id` ASC),
  INDEX `fk_medidor_medidorTerminal1_idx` (`medidorTerminal_id` ASC),
  INDEX `fk_medidor_medidorPendencias1_idx` (`medidorPendencias_id` ASC),
  INDEX `fk_medidor_medidorAtribGerais1_idx` (`medidorAtribGerais_id` ASC),
  CONSTRAINT `fk_medidor_medidorFamilia1`
    FOREIGN KEY (`medidorFamilia_id`)
    REFERENCES `tds`.`medidorFamilia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medidor_medidorDesenho1`
    FOREIGN KEY (`medidorImagem_id`)
    REFERENCES `tds`.`medidorImagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medidor_medidorTerminal1`
    FOREIGN KEY (`medidorTerminal_id`)
    REFERENCES `tds`.`medidorTerminal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medidor_medidorPendencias1`
    FOREIGN KEY (`medidorPendencias_id`)
    REFERENCES `tds`.`medidorPendencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medidor_medidorAtribGerais1`
    FOREIGN KEY (`medidorAtribGerais_id`)
    REFERENCES `tds`.`medidorAtribGerais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tds`.`medidorModelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tds`.`medidorModelo` ;

CREATE TABLE IF NOT EXISTS `tds`.`medidorModelo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `medidorFamilia_id` INT NOT NULL,
  PRIMARY KEY (`id`, `medidorFamilia_id`),
  INDEX `fk_medidorModelo_medidorFamilia1_idx` (`medidorFamilia_id` ASC),
  CONSTRAINT `fk_medidorModelo_medidorFamilia1`
    FOREIGN KEY (`medidorFamilia_id`)
    REFERENCES `tds`.`medidorFamilia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tds`.`caracteristica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tds`.`caracteristica` ;

CREATE TABLE IF NOT EXISTS `tds`.`caracteristica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_da_caracteristica` VARCHAR(45) NULL,
  `tipo` SET('LONGTEXT', 'INT', 'FLOAT', 'DATE') NULL,
  `valorPadrao` LONGTEXT NULL,
  `medidorAtribGerais_id` INT NOT NULL,
  PRIMARY KEY (`id`, `medidorAtribGerais_id`),
  INDEX `fk_caracteristica_medidorAtribGerais1_idx` (`medidorAtribGerais_id` ASC),
  CONSTRAINT `fk_caracteristica_medidorAtribGerais1`
    FOREIGN KEY (`medidorAtribGerais_id`)
    REFERENCES `tds`.`medidorAtribGerais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
